### ISSUE TITLE
Preloaded .jar files idea

### ISSUE THREAD

**Issue by EternalBones** [Lorenzo3421-git/LorMSM#3]
When creating a server, it would be very useful for there to be a preexisting folder 
with a preinstalled list of recent or popular Minecraft .jar files, such as versions 1.14.4, 1.15.2, 1.16.1, and 1.16.2.
Additionally, there could also be a readme document in this ".jars" folder showing the user how to find and install their own .jar files if they wish to play one of the versions of Minecraft that weren't already preloaded.

**Comment by Lorenzo3421-git** [comment]
I added a Jar Browser, check it out and tell me how it is! ^^
